import { ContextProvider } from '@/contexts/ContextProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/navbar'
import { ContentContainer } from '@/components/contentContainer'
import Notifications from '@/components/notifications'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
        <div className="flex flex-col h-screen w-screen">
          <Notifications />
          <Navbar />
          
            {children}
          
        </div>
        </ContextProvider>
      </body>
    </html>
  )
}


